#!/bin/bash
SETUPDIR="$HOME/.shell"
FILES="bash_profile bashrc zprofile zshrc vimrc profile"
for file in $FILES; do
	[ -L "$HOME/.$file" ] && rm "$HOME/.$file"
	[ -e "$HOME/.$file" ] && rm -i "$HOME/.$file"
	ln -s "$SETUPDIR/$file" "$HOME/.$file"
done
